const gulp = require('gulp')
const concat = require('gulp-concat')
const jshint = require('gulp-jshint')
const plumber = require('gulp-plumber')
const rename = require('gulp-rename')
const replace = require('gulp-replace')
const terser = require('gulp-terser')

gulp.task('default', () => {
  return gulp.src('src/client/**/*.js')
    .pipe(plumber())
    .pipe(jshint({ esversion: 12 }))
    .pipe(replace(/import.+/g, ''))
    .pipe(replace(/export\s/g, ''))
    .pipe(concat('client.js'))
    .pipe(terser())
    .pipe(rename('client.min.js'))
    .pipe(gulp.dest('./dist'))
})
